version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demo-saas-pooled"
s3_bucket = "demo-saas-sam-artifacts-d4dedf84"
s3_prefix = "demo-saas-tenant"
region = "ap-south-1"
profile = "sarowar-ostad"
confirm_changeset = false
capabilities = ["CAPABILITY_NAMED_IAM"]
parameter_overrides = "StackPrefix=demo-saas CognitoTenantUserPoolId=ap-south-1_HBp3JFapS CognitoTenantAppClientId=6977tq506586hi3t2o909j81m9"
cached = true
parallel = true











